[jn]
  title = "Tanzu User kNowledge Assembly Japan"
  LanguageName = "English"
  weight = 3

[en]
  title = "Clarity"
  LanguageName = "English"
  weight = 1

[pt]
  title = "Claridade" # just for the sake of showing this is possible
  LanguageName = "Português"
  weight = 2
  
